Ass1-war/src/fit5042/tutex/controllers/ContactController.java
package fit5042.tutex.controllers;
import java.util.ArrayList;
import javax.el.ELContext;

import fit5042.tutex.mbeans.CustomerManagedBean;
import fit5042.tutex.repository.entities.Contact;
import fit5042.tutex.repository.entities.Customer;

import javax.inject.Named;
import javax.enterprise.context.Dependent;
import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;

@Named(value = "contactController")
@RequestScoped
public class ContactController {
	 @ManagedProperty(value = "#{customerManagedBean}")
	    CustomerManagedBean customerManagedBean;
	 
	 private boolean showForm = true;
 
	 private int contactId; //this propertyId is the index, don't confuse with the Property Id
 
 CustomerApplication app;

 public int getContactId() {
     return contactId;
 }

 public void setContactId(int contactId) {
     this.contactId = contactId;
 }
 
 
 public CustomerApplication getCustomerApplication() {
		return app;
	}

	public void setCustomerApplication(CustomerApplication customerApplication) {
		this.app = customerApplication;
	}


	private fit5042.tutex.repository.entities.Contact contact;
	
	public ContactController() {
        // Assign property identifier via GET param 
        //this propertyID is the index, don't confuse with the Property Id
    	 ELContext context
         = FacesContext.getCurrentInstance().getELContext();
 app = (CustomerApplication) FacesContext.getCurrentInstance()
                 .getApplication()
                 .getELResolver()
                 .getValue(context, null, "customerApplication");
    	
    	contactId = Integer.valueOf(FacesContext.getCurrentInstance()
                .getExternalContext()
                .getRequestParameterMap()
                .get("contactID"));
        // Assign property based on the id provided 
    	contact = getContact();
     
       
    }
	
	 public fit5042.tutex.repository.entities.Contact getContact() {
	        if (contact == null) {
	            // Get application context bean PropertyApplication 
	           
	            // -1 to propertyId since we +1 in JSF (to always have positive property id!) 
	            return app.getContacts().get(--contactId); //this propertyId is the index, don't confuse with the Property Id
	        }
	        return contact;
	        
	        
	    }

}

Ass1-war/src/fit5042/tutex/controllers/user/ContactController.java
package fit5042.tutex.controllers.user;
import java.util.ArrayList;
import javax.el.ELContext;

import fit5042.tutex.mbeans.CustomerManagedBean;
import fit5042.tutex.repository.entities.Contact;
import fit5042.tutex.repository.entities.Customer;

import javax.inject.Named;
import javax.enterprise.context.Dependent;
import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;

@Named(value = "userContactController")
@RequestScoped
public class ContactController {
	 @ManagedProperty(value = "#{customerManagedBean}")
	    CustomerManagedBean customerManagedBean;
	 
	 private boolean showForm = true;
 
	 private int contactId; //this propertyId is the index, don't confuse with the Property Id
 
	 UserController app;

 public int getContactId() {
     return contactId;
 }

 public void setContactId(int contactId) {
     this.contactId = contactId;
 }
 

public UserController getApp() {
	return app;
}

public void setApp(UserController app) {
	this.app = app;
}


	private fit5042.tutex.repository.entities.Contact contact;
	
	public ContactController() {
        // Assign property identifier via GET param 
        //this propertyID is the index, don't confuse with the Property Id
    	 ELContext context
         = FacesContext.getCurrentInstance().getELContext();
 app = (UserController) FacesContext.getCurrentInstance()
                 .getApplication()
                 .getELResolver()
                 .getValue(context, null, "userController");
    	
    	contactId = Integer.valueOf(FacesContext.getCurrentInstance()
                .getExternalContext()
                .getRequestParameterMap()
                .get("contactID"));
        // Assign property based on the id provided 
    	contact = getContact();
     
       
    }
	
	 public fit5042.tutex.repository.entities.Contact getContact() {
	        if (contact == null) {
	            // Get application context bean PropertyApplication 
	           
	            // -1 to propertyId since we +1 in JSF (to always have positive property id!) 
	            return app.getContactList().get(--contactId); //this propertyId is the index, don't confuse with the Property Id
	        }
	        return contact;
	        
	        
	    }

}

Ass1-war/src/fit5042/tutex/mbeans/CustomerManagedBean.java
package fit5042.tutex.mbeans;
import fit5042.tutex.repository.CustomerRepository;
import fit5042.tutex.repository.entities.Address;
import fit5042.tutex.repository.entities.Contact;

import fit5042.tutex.repository.entities.Customer;
import fit5042.tutex.repository.entities.Groups;
import fit5042.tutex.repository.entities.IndustryType;
import fit5042.tutex.repository.entities.Users;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;


@ManagedBean(name = "customerManagedBean")
@SessionScoped
public class CustomerManagedBean implements Serializable{
	
	@EJB
	CustomerRepository customerRepository;
	
	private String checkPsw;
	
	
	
	
	public CustomerManagedBean() {
    }
	
	public String getCheckPsw() {
		return checkPsw;
	}

	public void setCheckPsw(String checkPsw) {
		this.checkPsw = checkPsw;
	}
	
	
	
	 	public Users searchUserByName(String userName) {
	        try {
	            Users user = customerRepository.searchUserByName(userName);
	            return user;
	        } catch (Exception ex) {
	            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }
	        return null;
	    }
	
	
	 	public List<Users> getAllUsers() {
		        try {
		            List<Users> users = customerRepository.getAllUsers();
		            return users;
		        } catch (Exception ex) {
		            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
		        }
		        return null;
		    }
	 	
	 	public List<IndustryType> getAllIndustry() {
	        try {
	            List<IndustryType> industryTypes = customerRepository.getAllIndustry();
	            return industryTypes;
	        } catch (Exception ex) {
	            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }
	        return null;
	    }
	 	
	 	
	 	
	   public List<Customer> getAllCustomers() {
	        try {
	            List<Customer> customers = customerRepository.getAllCustomers();
	            return customers;
	        } catch (Exception ex) {
	            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }
	        return null;
	    }
	
	   public void addCustomer(fit5042.tutex.controllers.Customer localCustomer) {
	        //convert this newProperty which is the local property to entity property
	        Customer customer = convertCustomerToEntity(localCustomer);
	        Users user = new Users();
	        user = localCustomer.getUser();
	        IndustryType industryType = new IndustryType();
	        industryType = localCustomer.getIndustryType();
	        
	        if (user.getUserId() == 0) {
	        	user = null;
	        }
	        
	        customer.setUser(user);
	        
	        if (industryType.getIndustryId() == 0) {
	        	industryType = null;
	        }
	        
	        customer.setIndustryType(industryType);

	        try {
	            customerRepository.addCustomer(customer);
	            
	        } catch (Exception ex) {
	            Logger.getLogger(CustomerRepository.class.getName()).log(Level.SEVERE, null, ex);
	        }
	        
	 
	    }
	   
	   public void addUserCustomer(fit5042.tutex.controllers.Customer localCustomer,fit5042.tutex.repository.entities.Users user) {
	        //convert this newProperty which is the local property to entity property
	        Customer customer = convertCustomerToEntity(localCustomer);
	        customer.setUser(user);
	        IndustryType industryType = new IndustryType();
	        industryType = localCustomer.getIndustryType();
	        
	        if (industryType.getIndustryId() == 0) {
	        	industryType = null;
	        }
	        
	        customer.setIndustryType(industryType);


	        try {
	            customerRepository.addCustomer(customer);
	            
	        } catch (Exception ex) {
	            Logger.getLogger(CustomerRepository.class.getName()).log(Level.SEVERE, null, ex);
	        }
	        
	 
	    }
	   
	   public void addContact(Customer customer,fit5042.tutex.controllers.Contact localContact) {
		   Contact contact = convertContactToEntity(customer,localContact);
		   try {
			   customerRepository.addContact(contact);
		   
		   }catch (Exception ex) {
	            Logger.getLogger(CustomerRepository.class.getName()).log(Level.SEVERE, null, ex);
	        }
		   
	   }
	   
	   
	   public void addUser(fit5042.tutex.controllers.User localUser) {
		   Users user = convertUserToEntity(localUser);
		   Groups group = new Groups();
		   group.setUsername(user.getUsername());
		   group.setGroupname("user");
		   try {
			   customerRepository.addUser(user);
			   customerRepository.addGroup(group);
			   FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("User has been added succesfully"));
		   }catch (Exception ex) {
			   FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("This user name is existing,please enter other user name"));
	            Logger.getLogger(CustomerRepository.class.getName()).log(Level.SEVERE, null, ex);
	        }
		   
	   }
	   
	   public void addIndustry(fit5042.tutex.controllers.Industry localIndustry) {
		
		   IndustryType industryType = new IndustryType();
		   industryType.setTypeName(localIndustry.getTypeName());
		   
		   try {
			   customerRepository.addIndustry(industryType);
		   
		   }catch (Exception ex) {
	            Logger.getLogger(CustomerRepository.class.getName()).log(Level.SEVERE, null, ex);
	        }
		   
	   }
	   
	   

	   
	   public Set<Contact> searchContactByCustomer(Customer customer) {
	        try {
	            return customerRepository.searchContactByCustomer(customer);
	        } catch (Exception ex) {
	            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }

	        return null;
	    }
	   
	   public Set<Customer> searchCustomerByUser(Users user) {
	        try {
	            return customerRepository.searchCustomerByUser(user);
	        } catch (Exception ex) {
	            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }

	        return null;
	    }
	   
	   public Set<Customer> searchCustomerByCountryAndIndustry(String country,int industryId){
		   
		   Set<Customer> filterCustomer = new HashSet<>();
		   try {
			   for (Customer customer: customerRepository.getAllCustomers())
			   {
				   if(customer.getCountry().equals(country) && customer.getIndustryType().getIndustryId() == industryId) 
				   {
					   filterCustomer.add(customer);
				   }
			   }
			   return filterCustomer;
		   }
		   catch(Exception ex){
			   
		   }
		   
		   return null;
	   }
	   
	   
	   
	    public void editContact(Contact contact) {
	        try {

	            customerRepository.editContact(contact);

	            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Contact has been updated succesfully"));
	        } catch (Exception ex) {
	            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }
	    }
	    
	    public void editCustomer(Customer customer) {
	        try {

	            customerRepository.editCustomer(customer);

	            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Customer has been updated succesfully"));
	        } catch (Exception ex) {
	            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }
	    }
	    
	    public void editUser(Users user,String localPassword) {
	    	String password = localPassword;
	    	
	    	try {
	    		String hashPassword = convertPasswordToSha256(password);
	    		user.setPassword(hashPassword);

	            customerRepository.editUser(user);

	            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Password has been updated succesfully"));
	        } catch (Exception ex) {
	            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }
	    }
	    
	    public void editIndustry(IndustryType industryType ) {
	        try {

	        	String typename = industryType.getTypeName();
	        	if(typename.equals("Bank") || 
		        		typename.equals("Building") || 
		        		typename.equals("Data Communication") ||
		        		typename.equals("Education") ||
		        		typename.equals("Farm") ||
		        		typename.equals("Health") ||
		        		typename.equals("Mining") ||
		        		typename.equals("Publishing") ) 
		        	{
		        	 customerRepository.editIndustry(industryType);

			            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Industry has been updated succesfully"));
		        	}
		        	
		        	else {
		        		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Industry Type must be from Bank,Building,Data Communication,"
		        				+ "Education,Farm,Health,Mining,Publishing"));
		        	}

	        } catch (Exception ex) {
	            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }
	    }
	    
	   
	   public void removeContact(int contactId) {
	        try {
	        	customerRepository.removeContact(contactId);
	 
	        } catch (Exception ex) {
	            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }
	    }
	   
	   public void removeCustomer(int customerId) {
	        try {
	        	customerRepository.removeCustomer(customerId);
	 
	        } catch (Exception ex) {

Ass1-war/WebContent/admin/add.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
        <title>Add Customer</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    Add Customer
                </div>
            </div>
            <div>
        <f:view>
            <h:form>
                <h1><h:outputText value="Create"/></h1>
                
                <table class="table table-bordered ">
                
                    <tr class="#{!name.valid ? 'has-error' : 'none'}">
                        <td width ="200">
                            <h:outputLabel value="name" for="name" />
                        </td>
                        <td>
                            <h:inputText id="name" value="#{customer.name}" title="Name" required="true" requiredMessage="Please enter the street number!" validatorMessage="Please enter name" pt:placeholder="Default Customer">
	    
							</h:inputText>
                            <br/>
                            <h:message for="name" class="#{!name.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    </tr>

                    <tr class="#{!streetNumber.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="streetNumber" for="streetNumber" />
                        </td>
                        <td>
                            <h:inputText id="streetNumber" value="#{customer.streetNumber}" title="streetNumber" required="true" requiredMessage="Please enter the streetNumber!" pt:placeholder="1000"/>
                            <br/>
                            <h:message for="streetNumber" class="#{!streetNumber.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                         <tr class="#{!street.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="street" for="street" />
                        </td>
                        <td>
                            <h:inputText id="street" value="#{customer.streetAddress}" title="street" required="true" requiredMessage="Please enter the street!" pt:placeholder="clayton road"/>
                            <br/>
                            <h:message for="street" class="#{!street.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
         
                    
                <tr class="#{!suburb.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="suburb" for="suburb" />
                        </td>
                        <td>
                            <h:inputText id="suburb" value="#{customer.suburb}" title="suburb" required="true" requiredMessage="Please enter the suburb!" pt:placeholder="Caulfield East"/>
                        	<br/>
                            <h:message for="suburb" class="#{!suburb.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr class="#{!state.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="state" for="state"/>
                        </td>
                        <td>
                            <h:inputText id="state"  value="#{customer.state}" title="state" size="3" required="true" requiredMessage="Please enter the state!" pt:placeholder="VIC"/>
                            <br/>
                            <h:message for="state" class="#{!state.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    <tr class="#{!postcode.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="postcode" for="postcode" />
                        </td>
                        <td>
                            <h:inputText id="postcode" value="#{customer.postcode}"  title="postcode" required="true" requiredMessage="Please enter the postcode!" validatorMessage="Please enter a postcode between 0200 and 4700" converterMessage="Please enter a number" pt:placeholder="3145">
	                            <f:convertNumber integerOnly="true"/>
								<f:validateLongRange minimum="200" maximum="4700" /> 
							</h:inputText>
							<br/>
							<h:message for="postcode" class="#{!postcode.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    
                    
                    <tr class="#{!country.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="country" for="country" />
                        </td>
                        <td>
                            <h:inputText id="country" value="#{customer.country}" title="country" required="true" requiredMessage="Please enter the country!" pt:placeholder="AUS"/>
                        	<br/>
                            <h:message for="country" class="#{!country.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr class="#{!found.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="found" for="found"/>
                        </td>
                        <td>
                            <h:inputText id="found" value="#{customer.foundingDate}" title="found"  required="true" validatorMessage="Founding Year Format:2000-01-01" requiredMessage="Please enter the foundation date!" pt:placeholder="2000-01-01">
                            <f:validateRegex  pattern="([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))"/>
                            </h:inputText>
                            <br/>
                            <h:message for="found" class="#{!found.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    <tr>
							<td><h:outputLabel value="Industry Type:" for="industry" /></td>
							<td><h:selectOneMenu id="industry"
									value="#{customer.industryType}" converter="industry">
									<f:selectItem itemValue="#{null}" itemLabel="--select--" />
									<f:selectItems value="#{customerManagedBean.allIndustry}"
										var="c" itemLabel="#{c.typeName}" itemValue="#{c}" />
								</h:selectOneMenu></td>
						</tr>
                    
                    <tr class="#{!introduction.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="introduction" for="introduction" />
                        </td>
                        <td>
                            <h:inputText id="introduction" value="#{customer.introduction}" title="type" required="true" requiredMessage="Please enter the Introduction"  pt:placeholder="Intro">
	           
							</h:inputText>
							<br/>
							<h:message for="introduction" class="#{!introduction.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                     <tr class="#{!website.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="website" for="website" />
                        </td>
                        <td>
                            <h:inputText id="website" value="#{customer.website}" title="website" required="true" requiredMessage="Please enter the website"  pt:placeholder="websitewww">
	           
							</h:inputText>
							<br/>
							<h:message for="website" class="#{!website.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                     <tr>
							<td><h:outputLabel value="User:" for="user" /></td>
							<td><h:selectOneMenu id="user"
									value="#{customer.user}" converter="user">
									<f:selectItem itemValue="#{null}" itemLabel="--select--" />
									<f:selectItems value="#{customerManagedBean.allUsers}"
										var="c" itemLabel="#{c.username}" itemValue="#{c}" />
								</h:selectOneMenu></td>
						</tr>
                    
                </table>
                
                <h:commandButton id="submit" value="Submit" action="#{addCustomer.addCustomer(customer)}" 
                class="btn btn-primary" >
                </h:commandButton>
                <h:link id="close" value="Close" outcome="/admin/index"
						class="btn btn-primary" />
            	
            </h:form>
			
        </f:view>
            </div>
        </div>
       
    </h:body>
</html>

Ass1-war/WebContent/admin/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"> 
 <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>Administration Area</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                   #{userController.userName}
                </div>
            </div>

            <h:form id="MyForm">
                <table class="table table-bordered table-striped">
                    <!-- For each property in properties ArrayList... --> 
                    <tr>
                            <td> 
                                <h:outputLabel id="Id" value="Id"  />
                            </td>
                            <td> 
                                <h:outputLabel id="Name" value="Name"  />
                            </td>
          
                            <td> 
                                <h:outputLabel id="Address" value="Address"/>
                            </td>
                            <td> 
                                <h:outputLabel id="Country" value="Country"  />
                            </td>
                               <td> 
                                <h:outputLabel id="IndustryType" value="Industry Type"  />
                            </td>
                            
                     </tr>
                     
                     <ui:repeat id="Myrepeat" value="#{customerApplication.customers}"  var="customer" varStatus="status"> 
                        
                        <tr> 
                            <td>
                                <h:outputText value="#{customerApplication.customers.get(status.index).customerId}" id="customerID" /> 
                                
                            </td>
                            
                            <td> 
                                <h:outputText id="outName" value="#{customerApplication.customers.get(status.index).name}"  />
                            </td>
                            
                            <td>
                                <h:outputText id="outAddress" value="#{customerApplication.customers.get(status.index).address}"/>
                            </td>
                            
                            <td>
                                <h:outputText id="outCountry" value="#{customerApplication.customers.get(status.index).country}"/>
                            </td>
                            <td>
                                <h:outputText id="outIndustry" value="#{customerApplication.customers.get(status.index).industryType.typeName}"/>
                            </td>
    
                          <td>
                                <h:link value="View" outcome="/admin/customerDetail">
                                <!-- pass the parameter to next page, the param name is propertyID, and the value is index + 1.
                                  You can get the value from next page using the indexController -->
                                  <f:param name="customerID" value="#{status.index + 1}"/>
                                </h:link>
                                	<h:link value="Edit" outcome="/admin/edit">
                                <!-- pass the parameter to next page, the param name is propertyID, and the value is index + 1.
                                  You can get the value from next page using the indexController -->
                                  <f:param name="customerID" value="#{status.index + 1}"/>
                                </h:link>
                                 <h:link value="View Contact" outcome="/admin/contact">
                                <!-- pass the parameter to next page, the param name is propertyID, and the value is index + 1.
                                  You can get the value from next page using the indexController -->
                                  <f:param name="customerID" value="#{status.index + 1}"/>
                                </h:link>
 							
                    
                            </td>
                            
                        </tr> 

                    </ui:repeat>
                    
                </table> 
                <div>
                Country:
                <h:inputText value="#{searchCustomer.country}" id="searchByCountry" />
                Industry Type:
                <h:selectOneMenu id="industry" value="#{searchCustomer.industryTypeId}">
									<f:selectItem itemValue="#{null}" itemLabel="--select--" />
									<f:selectItems value="#{customerManagedBean.allIndustry}"
										var="c" itemLabel="#{c.typeName}" itemValue="#{c.industryId}" />
				</h:selectOneMenu>
                  <h:commandButton id="searchByCountryIndustry" value="Search By Country and Industry Type" action="#{searchCustomer.searchCustomerByCountryAndIndustry(searchCustomer.country,searchCustomer.industryTypeId)}" class="btn btn-primary" >
                        <f:param name="customerID" value="#{status.index + 1}"/>
                    </h:commandButton>
                      <h:commandButton id="searchAll" value="All Customer" action="#{searchCustomer.searchAll()}" class="btn btn-primary" >
                        <f:param name="customerID" value="#{status.index + 1}"/>
                    </h:commandButton>
                </div>
                <div>
                
                </div>
                
                <div>
                    <h:commandButton id="add" value="Add Customer" action="/admin/add" class="btn btn-primary" />
                </div>
                <div>
                	<h:commandButton id="manageUser" value="Manage Users" action="/admin/manageUser" class="btn btn-primary" />
                </div>
                <div>
                    <h:commandButton id="manageIndustry" value="Manage Industry Type" action="/admin/manageIndustry" class="btn btn-primary" />
               </div>
            </h:form>
        </div>
    </h:body>

</html>

<!--   -->